version: '3'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8-management
    volumes:
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
      RABBITMQ_DEFAULT_VHOST: sample
